name: 'dockdesk'
description: 'AI Auditor that ensures Code matches Documentation.'
author: 'Srivatsa'
branding:
  icon: 'shield'  # Options: shield, lock, check, search, eye
  color: 'blue'   # Options: blue, green, yellow, red, purple
inputs:
  openai_api_key:
    description: 'API Key (Gemini or OpenAI)'
    required: true
  github_token:
    description: 'GitHub Token for commenting'
    required: true
  code_file:
    description: 'Path to code file (Leave as "AUTO" to scan PR changes)'
    required: false
    default: 'AUTO'
  doc_file:
    description: 'Path to doc file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.code_file }}
    - ${{ inputs.doc_file }}
  env:
    # 🚨 CRITICAL FIX: Map the input 'openai_api_key' to the env var 'OPENAI_API_KEY'
    # The Python script reads os.getenv("OPENAI_API_KEY"), so this must match!
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
